### ISSUE TITLE
Setup auth

### ISSUE THREAD

**Issue by Moeriki** [OpenSkool/OpenSkool#137]
## To Do

- [x] Setup Keycloak database / server on local
- [x] Figure out config / realms / etc
- [x] Integrate app/api authentication: App can login using keycloak. GraphQL knows who's who.
- [x] Add app state: App knows who's logged in. Can log in and out.
- [x] Replace demo user with domain user.

## Split up

- [x] #151

In order of likely priority. Will probably be implemented when we need it.

- [ ] #152
- [ ] #153
- [ ] #154
- [ ] #155
- [ ] #156
- [x] #157
- [ ] #158

## Resources

- https://github.com/keycloak/keycloak-nodejs-connect
- https://github.com/keycloak/keycloak-quickstarts/tree/latest/service-nodejs
- https://github.com/keycloak/keycloak-quickstarts/tree/latest/applications/app-vue
- https://github.com/keycloak/keycloak-nodejs-admin-client
- https://github.com/thomasdarimont/awesome-keycloak
- https://github.com/fastify/session
- https://www.securecoding.com/blog/session-management-an-overview/
- https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html
- https://www.youtube.com/playlist?list=PLPZal7ksxNs0mgScrJxrggEayV-TPZ9sA

**Comment by Moeriki** [comment]
Ticket is done. But merge to main depends on #151 to be done!

**Comment by Moeriki** [comment]
This ticket can be closed. All follow up will happen in linked tickets.

**Comment by SiteSeerBE** [comment]
Error on logout needs to be resolved.
"Missing parameters: id_token_hint"

**Comment by Moeriki** [comment]
> Error on logout needs to be resolved.
> "Missing parameters: id_token_hint"

Fixed on dev.

**Comment by Moeriki** [comment]
The auth middleware crashes sometimes on GraphQL API calls.

https://github.com/OpenSkool/OpenSkool/blob/main/api/src/api/auth.ts#L27

It seems the session is not always set. I haven't found an exact reproduction yet.

**Comment by Moeriki** [comment]
API response.

<img width="652" alt="CleanShot 2022-04-27 at 11 57 29@2x" src="https://user-images.githubusercontent.com/38758/165493227-6b9ba311-067f-4e9d-91d2-6be0d07c6036.png">

API error

```
[openskool-api] [2022-04-27 09:56:55] {"level":50,"time":1651053415420,"pid":200,"hostname":"openskool-api-8c79bfbc9-j7s8x","isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}},"stack":"TypeError: Cannot read properties of null (reading 'auth')\n    at Object.authRequestHook (/workspace/api/dist/api/auth.js:33:11)\n    at hookIterator (/workspace/node_modules/fastify/lib/hooks.js:237:10)\n    at next (/workspace/node_modules/fastify/lib/hooks.js:164:16)\n    at handleResolve (/workspace/node_modules/fastify/lib/hooks.js:175:5)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","msg":"Cannot read properties of null (reading 'auth')"}
```

**Comment by SiteSeerBE** [comment]
Auth error appears after exactly 5 minutes.
